# Generated by Django 3.1.3 on 2021-01-26 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surpresseur',
            fields=[
                ('plc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.plc')),
                ('pression', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
            ],
            bases=('front.plc',),
        ),
        migrations.AlterField(
            model_name='plc',
            name='slave_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
