# Generated by Django 3.1.3 on 2021-01-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20210126_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.IntegerField()),
                ('is_bit', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('PLC', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='front.plc')),
            ],
            options={
                'unique_together': {('PLC', 'address', 'is_bit')},
            },
        ),
        migrations.CreateModel(
            name='MeasuresValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('value_type', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField()),
                ('measure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='front.measures')),
            ],
        ),
    ]
